# 개발 단계에서 편하게 DB 확인 & 테이블 자동 생성하려는 설정
# 실제 배포 환경에서는 ddl-auto: update 대신 validate 또는 none을,
# DB도 MySQL/PostgreSQL 같은 외부 DB를 쓴다.

spring:
  datasource:  # 데이터 베이스 연결 설정
    url: jdbc:h2:mem:todo;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa  # H2 기본 사용자 이름
    password:  # H2 기본은 비밀번호 없음
  jpa:
    hibernate:
      ddl-auto: update
      # 애플리케이션 실행 시 엔티티(Entity) 구조에 맞춰 DB 테이블 자동 생성/업데이트

    show-sql: true  # 콘솔에 실행되는 SQL 쿼리 출력
  h2:
    console:
      enabled: true  # H2 웹 콘솔 사용 가능 (http://localhost:8080/h2-console 접속)
